# Generated by Django 4.1.5 on 2023-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=64, unique=True, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('movie_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('release_date', models.DateField(verbose_name='Release date')),
            ],
        ),
    ]
